/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	System.out.println("Test: testSomeLibraryMethod()");
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test public void testToFail() {
    	System.out.println("Test: testToFail()");
        Library classUnderTest = new Library();
        assertFalse("Expect to fail", classUnderTest.someLibraryMethod());
    }
}
